language: node_js
sudo: true
services:
  - mysql
node_js: "11"
before_install:
  - mysql -e "CREATE DATABASE IF NOT EXISTS test; USE test; CREATE TABLE message_history(id BIGINT(20) UNSIGNED AUTO_INCREMENT PRIMARY KEY, message VARCHAR(255) NOT NULL, mediaUrl VARCHAR(255), sender BIGINT(20) NOT NULL, created_at TIMESTAMP, updated_at TIMESTAMP); CREATE TABLE users(id BIGINT(20) UNSIGNED AUTO_INCREMENT PRIMARY KEY, fname VARCHAR(255) NOT NULL, lname VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL UNIQUE, password VARCHAR(255) NOT NULL, super TINYINT(1) NOT NULL DEFAULT 0, created_at TIMESTAMP, updated_at TIMESTAMP, deleted_at TIMESTAMP); "CREATE TABLE subscribers(id BIGINT(20) UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255), phone BIGINT(20) UNSIGNED NOT NULL UNIQUE, created_at TIMESTAMP, updated_at TIMESTAMP); CREATE TABLE user_requests(id BIGINT(20) UNSIGNED AUTO_INCREMENT PRIMARY KEY, fname VARCHAR(255) NOT NULL, lname VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL UNIQUE, created_at TIMESTAMP, updated_at TIMESTAMP);"
install: npm install
before_script: npm install -g forever
script: npm test
