language: node_js
sudo: true
services:
  - mysql
node_js: "11"
before_install:
  - mysql -e "use mysql; update user set authentication_string=PASSWORD('new_password') where User='travis'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test; USE test;'
install: npm install
before_script: npm install -g forever
script: npm test
after_failure:
  - mysql -e 'show databases;'
